package pmsystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author busta
 */
public class forgotpass extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public forgotpass() {
        initComponents();
        con = db.mycon();
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/" + "monitoringsystemdb", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Email13 = new javax.swing.JLabel();
        Email14 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtquestion = new javax.swing.JTextField();
        txtanswer = new javax.swing.JTextField();
        Email15 = new javax.swing.JLabel();
        Email16 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Email17 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtcpass = new javax.swing.JPasswordField();
        btnclear = new javax.swing.JButton();
        checkc = new javax.swing.JCheckBox();
        check = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmsystem/PMS-FRONT.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email13.setForeground(new java.awt.Color(255, 255, 255));
        Email13.setText("EMAIL:");
        jPanel1.add(Email13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        Email14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email14.setForeground(new java.awt.Color(255, 255, 255));
        Email14.setText("SECURITY QUESTION:");
        jPanel1.add(Email14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 350, -1));

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));
        jPanel1.add(txtquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 360, -1));
        jPanel1.add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 370, -1));

        Email15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email15.setForeground(new java.awt.Color(255, 255, 255));
        Email15.setText("ANSWER:");
        jPanel1.add(Email15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Email16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email16.setForeground(new java.awt.Color(255, 255, 255));
        Email16.setText("CONFIRM PASSWORD:");
        jPanel1.add(Email16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, -1));

        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back to login page?");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, 20));

        jLabel35.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 52)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("RESET PASSWORD");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        Email17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email17.setForeground(new java.awt.Color(255, 255, 255));
        Email17.setText("NEW PASSWORD:");
        jPanel1.add(Email17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 360, 30));
        jPanel1.add(txtcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 360, -1));

        btnclear.setBackground(new java.awt.Color(0, 51, 255));
        btnclear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR ALL");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        checkc.setForeground(new java.awt.Color(255, 255, 255));
        checkc.setText("show password");
        checkc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkcActionPerformed(evt);
            }
        });
        jPanel1.add(checkc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("show password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
    int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to clear all fields?", "Confirmation", JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
         new login().setVisible(true);
         this.setVisible(false);;
    }
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try{
        pst = con.prepareStatement("select question from registration where email=?");
        pst.setString(1, txtemail.getText());
        rs = pst.executeQuery();
        if(rs.next()){
            txtquestion.setText(rs.getString("question"));
        } else{
            JOptionPane.showMessageDialog(this, "Sorry, the email you entered doesn't exists.");
        }
        
        } catch (SQLException ex) {
            Logger.getLogger(forgotpass.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
   try {
        pst = con.prepareStatement("SELECT * FROM registration WHERE email=? AND answer=?");
        pst.setString(1, txtemail.getText());
        pst.setString(2, txtanswer.getText());
        rs = pst.executeQuery();

        if (!(new String(txtpassword.getPassword()).equals(new String(txtcpass.getPassword())))) {
            JOptionPane.showMessageDialog(this, "Your Passwords do not Match!");
            return;
        }

        if (rs.next()) {
            try {
                pst = con.prepareStatement("UPDATE registration SET password=?, cpass=? WHERE email=? AND answer=?");
                pst.setString(1, txtpassword.getText());
                pst.setString(2, txtcpass.getText());
                pst.setString(3, txtemail.getText());
                pst.setString(4, txtanswer.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Reset Successful. You can now log in with your new password.");
                
             this.setVisible(false);
             new login().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(forgotpass.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "An error occurred while resetting your password.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Email and Answer combination not found.");
        }

    } catch (SQLException ex) {
        Logger.getLogger(forgotpass.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "An error occurred while verifying your information.");
    }

        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtemail.setText("");
        txtquestion.setText("");
        txtanswer.setText("");
        txtpassword.setText("");
        txtcpass.setText("");
        txtpassword.setText("");
        txtcpass.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void checkcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkcActionPerformed
        if(checkc.isSelected()) {
            txtcpass.setEchoChar((char)0);
        }
        else {
            txtcpass.setEchoChar('*');
        }
    }//GEN-LAST:event_checkcActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if(check.isSelected()) {
            txtpassword.setEchoChar((char)0);
        }
        else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email13;
    private javax.swing.JLabel Email14;
    private javax.swing.JLabel Email15;
    private javax.swing.JLabel Email16;
    private javax.swing.JLabel Email17;
    private javax.swing.JLabel back;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JCheckBox check;
    private javax.swing.JCheckBox checkc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JPasswordField txtcpass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtquestion;
    // End of variables declaration//GEN-END:variables
}
